#!/bin/sh
# Find and raise an existing gnome-terminal window. Otherwise, open a new one.
#   Copyright © 2010 Paul Kishimoto <mail@paul.kishimoto.name>
#   Made available under the GPLv3 (http://www.gnu.org/licenses/gpl-3.0.html)
#
# Requires the Ubuntu package 'wmctrl'.
#
# Use this with a GNOME keyboard shortcut and screen (or byobu) to always have
# a terminal at your fingertips. Running this script will find a gnome-terminal
# window that is minimized, below other windows, and/or on another desktop. The
# window will be brought to the current desktop, raised and given focus.
#
# It can be safely put in your local PATH; if it is called with arguments, they
# are passed on to the *real* gnome-terminal.

if [ $# -ne 0 ]; then
  /usr/bin/gnome-terminal $*
  exit 0
fi
GTPID=`ps --user $USER -o pid:1,command | grep -E "^[0-9]+ (/usr/bin/)?gnome-terminal" | cut -d" " -f 1`
if [ -n "$GTPID" ]; then
  GTWIN=`wmctrl -lp | grep " $GTPID " | cut -d" " -f 1`
fi
if [ -n "$GTWIN" ]; then
  wmctrl -iR $GTWIN
else
  exec /usr/bin/gnome-terminal
fi
