#!/bin/sh
# Alarm clock using Music Player Daemon (MPD)
#
# Copyright © 2010-2011 Paul Natsuo Kishimoto <mail@paul.kishimoto.name>
# Made available under the GPLv3 (http://www.gnu.org/licenses/gpl-3.0.html)
#
# Requires the Ubuntu packages 'mpc' and 'pulseaudio-utils'.
#
# To use, edit MPD_HOST to indicate which MPD instance to control. See the
# 'mpc' manpage for details. Then run this script with two arguments: an hour
# (0-23) and minute (0-59). For example:
#   $ rise-and-shine 16 30
# ...sets the alarm (e.g. for 4:30 PM).
#
# The script adds itself to your crontab. At the specified time, it lowers the
# volume of your default PulseAudio output to mute. It begins playing whatever
# is in your MPD playlist. Then, it slowly raises the volume back to its
# original level.
#
# You can set the RAMP_TIME (in seconds) for a more abrupt or gradual wakeup.
#
# Because of the format of crontab entries, you can also disable the alarm
# using:
#  $ rise-and-shine 0 \#0

start_alarm () {
  # settings
  MPD_HOST_MAC="--broadcast 10.42.44.255 00:0f:ea:60:15:38"
  MPD_HOST=192.168.1.2
  MPD_PASS=1blue6banana5
  RAMP_TIME=30
  MPC="mpc --quiet --host $MPD_PASS@$MPD_HOST"

  ## retrieve current PulseAudio volume
  #VOLUME=`pacmd dump | grep set-sink-volume | head -n 1 | cut -d " " -f 3`
  ## mute PulseAudio output
  #pacmd set-sink-volume 0 0x0 >/dev/null

  ## optional: wake the target
  #powerwake $MPD_HOST_MAC
  #sleep 90

  # start playing
  $MPC play
  # retrieve current MPD volume
  VOLUME="0"
  VOLSTEP="0"
  while [ $VOLSTEP -eq 0 ]; do
    VOLUME=$($MPC volume | sed 's@volume:[ ]*\([^% ]*\).*@\1@')
    if [ "$VOLUME" != "n/a" ]; then
      # steps from zero to target volume
      if [ $VOLUME -ge $RAMP_TIME ]; then
        VOLSTEP=$((VOLUME / RAMP_TIME))
      else
        # when RAMP_TIME < VOLUME integer division yields 0
        VOLSTEP="1"
      fi
    fi
  done

  # mute MPD directly
  $MPC volume 0

  # gradually increase volume over $RAMP_TIME seconds…
  for i in $(seq 0 $VOLSTEP $VOLUME)
  do
    ## …using PulseAudio.
    #pacmd set-sink-volume 0 `printf "0x%X" $i` >/dev/null
    # …using MPD.
    $MPC volume $i
    sleep 1
  done
  exit 0
}


set_alarm () {
  # name of the current script
  SCRIPT=$(which $0)
  # sed command to change the time of the alarm
  NEW_LINE="$2 $1 \* \* \* $SCRIPT"
  SED_CMD="s@^.*${SCRIPT}\$@${NEW_LINE}@"
  # edit the crontab
  crontab -l | sed --expression="${SED_CMD}" | crontab -
  exit 0
}


set_alarm_interactive () {
  if [ -z "$DISPLAY" ]; then
    echo $0 ": could not get \$DISPLAY"
    exit 1
  fi
  # name of the current script
  SCRIPT=$(basename $0)
  # use GUI dialog to get new time
  NEW_TIME=$(crontab -l | awk -F/ '/'$SCRIPT'/ {print $1}' | python $0.py)
  # sed command to change the time of the alarm
  SED_CMD="s@^[^/]*\($(which $0)\)@${NEW_TIME} \1@"
  # edit the crontab
  crontab -l | sed -e "${SED_CMD}" | crontab -
  exit 0
}


case $# in
0)
  start_alarm
  ;;
1)
  if [ "$1" = "--set" ]; then
    set_alarm_interactive
  else
    echo $0 ": invalid syntax"
    exit 1
  fi
  ;;
2)
  set_alarm $1 $2
  ;;
*)
  echo $0 ": invalid number of options."
  exit 1
  ;;
esac
