#!/bin/sh
# Notify of taskwarrior tasks
#
# Stolen shamelessly from https://github.com/flickerfly/taskwarrior-notifications
#
# Depends on a report 'notify' being defined in the .taskrc file. An example
# configuration is:
#
#   report.notify.columns=description.desc
#   report.notify.filter=status:pending start.any:
notify-send "Active tasks" "`task notify | tail -n +4 | head -n -2`"
